# Generated by Django 5.2.4 on 2025-08-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderproduct_is_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="is_added",
        ),
    ]
