# Generated by Django 5.2.4 on 2025-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="is_active",
        ),
    ]
