# Generated by Django 5.2.4 on 2025-08-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_remove_account_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
