# Generated by Django 5.2.4 on 2025-08-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_userprofile_address_line_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
