# Generated by Django 5.2.4 on 2025-08-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_userprofile_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
    ]
