# Generated by Django 5.2.4 on 2025-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=100, unique=True)),
                ("slug", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, max_length=200)),
                (
                    "cat_image",
                    models.ImageField(blank=True, upload_to="photos/categories"),
                ),
            ],
            options={
                "verbose_name": "Categorie",
                "verbose_name_plural": "Categories",
            },
        ),
    ]
