# Generated by Django 5.2.4 on 2025-07-31 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categorie",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
