# Generated by Django 5.2.4 on 2025-08-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_categorie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
