# Generated by Django 5.2.4 on 2025-08-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
