# Generated by Django 5.2.4 on 2025-08-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cartitem_total_price"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(to="store.variation"),
        ),
    ]
