# Generated by Django 5.2.4 on 2025-08-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0003_cartitem_variation"),
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="variation",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
